#
# On chargebyte platforms, a dedicated partition (128 MiB) is used for /var/log,
# so that we can use persistent journals.
# Note: the current version of systemd does not accept percent values yet.
#
[Journal]
Storage=persistent
SystemMaxUse=96M
MaxRetentionSec=7days
MaxFileSec=1day
