#
# On chargebyte platforms, a dedicated partition (128 MiB) is used for /var/log,
# so that we can use persistent journals without letting logs consume the rest
# of the system storage.
#
# Note: systemd 250 does not accept percent values for these settings.
#
[Journal]
Storage=persistent
SystemMaxUse=96M
SystemKeepFree=12M
SystemMaxFileSize=8M
MaxRetentionSec=7days
MaxFileSec=1day
