#!/bin/sh
#
# This script copies some configuration file from current running system
# to the updated partition (new system).
#

SLOT_CLASS="$1"
SLOT_MOUNT_POINT="$2"
BUNDLE_MOUNT_POINT="$3"

if [ "$SLOT_CLASS" = "rootfs" ]; then
	# source helper
	. "$BUNDLE_MOUNT_POINT/post-install.d/00-tar-helper"

	( xargs tar -c $IGNORE_FAILED_READ -C / ) <<-EOF | tar -x -C "$SLOT_MOUNT_POINT"
	/etc/hostname
	/etc/hosts
	/etc/machine-id
	/etc/localtime
	/etc/timezone
	/etc/ssh/ssh_host_ecdsa_key
	/etc/ssh/ssh_host_ecdsa_key.pub
	/etc/ssh/ssh_host_ed25519_key
	/etc/ssh/ssh_host_ed25519_key.pub
	/etc/ssh/ssh_host_rsa_key
	/etc/ssh/ssh_host_rsa_key.pub
	/home/root/.ssh
	/etc/systemd/network
	/etc/hostapd/hostapd.conf
	EOF

	# copy /etc/resolv.conf only if it is a plain file and not a link;
	# copy it also only when not migrating from Debian based OS to Yocto
	if [ -f /etc/resolv.conf -a ! -L /etc/resolv.conf -a ! -f /etc/debian_version ]; then
		rm -f "$SLOT_MOUNT_POINT/etc/resolv.conf"
		cat /etc/resolv.conf > "$SLOT_MOUNT_POINT/etc/resolv.conf"
	fi

	# migrate older /root to /home/root if present
	if [ -d /root/.ssh ]; then
		( xargs tar -c $IGNORE_FAILED_READ -C / ) <<-EOF | tar -x -C "$SLOT_MOUNT_POINT/home"
		/root/.ssh
		EOF
	fi
fi
