#!/bin/sh
#
# Trigger a reboot after the bundle finished installing, if the file
# /run/firmware-update-reboot-requested exists, otherwise do nothing.
#
# If the update has been performed by a service which might be already stopped
# due to configuration sync, the reboot can be automatically triggered as last step of the
# installation process.

SLOT_CLASS="$1"
SLOT_MOUNT_POINT="$2"
BUNDLE_MOUNT_POINT="$3"

# Only reboot after the final slot was installed
if [ "$SLOT_CLASS" != "customerfs" ]; then
	exit 0
fi

REBOOT_REQUESTED_FILE=/run/firmware-update-reboot-requested
if [ ! -f "$REBOOT_REQUESTED_FILE" ]; then
    exit 0
fi

logger -t rauc-post-install "Bundle installation finished and a reboot has been requested using $REBOOT_REQUESTED_FILE"
sync

# Prefer systemd reboot if available
if command -v systemctl >/dev/null 2>&1; then
	systemctl reboot
else
	reboot
fi
